# Generated by Django 4.0.6 on 2022-07-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('releaseDate', models.CharField(default='', max_length=10)),
                ('genre', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
